# Generated by Django 4.2.2 on 2023-06-22 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 13, 39, 1, 152198, tzinfo=datetime.timezone.utc)),
        ),
    ]
