# Generated by Django 4.2.2 on 2023-06-22 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 22, 13, 42, 48, 48275, tzinfo=datetime.timezone.utc)),
        ),
    ]
